version: '2'
services:
  jeecg-boot-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: jeecg-boot-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password

  jeecg-boot-redis:
    image: redis:5.0
    hostname: jeecg-boot-redis

  jeecg-boot-system:
    image: vulhub/jeecg-boot:3.5.3
    depends_on:
      - jeecg-boot-mysql
      - jeecg-boot-redis
    hostname: jeecg-boot-system
    ports:
      - 8080:8080
