services:
 node:
   build: .
   depends_on:
    - db
   ports:
    - "3000:3000"
   volumes:
    - ./www:/usr/src/www
 db:
   image: postgres:9.6
   environment: 
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=example
   volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql