services:
  web:
    image: vulhub/cacti:1.2.28
    ports:
     - "8080:80"
    depends_on:
     - db
    entrypoint:
     - bash
     - /entrypoint.sh
    volumes:
     - ./entrypoint.sh:/entrypoint.sh
    command: apache2-foreground
  db:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cacti
   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   ports:
    - "3306:3306"
