version: '2'
services:
 web:
   image: vulhub/teamcity:2023.05.3
   ports:
    - "8111:8111"
    - "5005:5005"
   environment:
    - TEAMCITY_SERVER_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
