management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
      - id: index
        uri: http://example.com
        predicates:
        - Method=GET
