version: "3.5"
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=chamilo
      - MYSQL_PASSWORD=chamilo
      - MYSQL_DATABASE=chamilo
    labels:
      "project.id": "docker.compose.mariadb"
      "project.github.url": "https://github.com/22phuber/docker-compose-chamilo-lms"
  chamilo_php7:
    build:
      context: ../../base/chamilo/1.11.18/ 
      target: php7_apache_chamilo_lms
      args:
        - CHAMILO_VERSION=1.11.18
        - CHAMILO_TAR=chamilo-1.11.18-php74.tar.gz
    links:
      - mariadb
    ports:
      - "8080:80"
    extra_hosts:
      - "docker.chamilo.net:127.0.0.1"
    labels:
      "project.id": "docker.compose.chamilo_lms"
      "project.github.url": "https://github.com/22phuber/docker-compose-chamilo-lms"
