services:
 master:
   image: vulhub/spark:2.3.1
   ports:
    - "8080:8080"
    - "7077:7077"
    - "6066:6066"
 slave:
   command: "slave spark://master:7077"
   image: vulhub/spark:2.3.1
   depends_on:
    - master
   ports:
    - "8081:8081"
