version: '2'
services:
 tomcat:
   image: vulhub/tomcat:8.0
   volumes:
    - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    - ./context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml
   ports:
    - "8080:8080"