version: '2'
services:
 nginx:
   image: nginx:1
   volumes:
    - ./www/index.php:/usr/share/nginx/html/index.php
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php
   ports:
    - "8080:80"
 php:
   image: vulhub/php:httpoxy
   volumes: 
    - ./www/index.php:/var/www/html/index.php