version: '2'
services:
 web:
   image: vulhub/phpmyadmin:4.8.1
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8080:80"
   depends_on:
    - mysql
 mysql:
   image: mysql:5.5
   environment: 
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test