version: '2'
services:
 web:
   image: vulhub/jimureport:1.6.0
   depends_on:
    - db
   environment: 
    - MYSQL_HOST=db
    - MYSQL_PORT=3306
    - MYSQL_DB=jimureport
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
   ports:
    - "8085:8085"
    - "5005:5005"
 db:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=jimureport
