version: '2'
services:
 ecshop27:
   image: vulhub/ecshop:2.7.3
   depends_on:
    - mysql
   ports:
    - "8080:80"
 ecshop36:
   image: vulhub/ecshop:3.6.0
   depends_on:
    - mysql
   ports:
    - "8081:80"
 mysql:
   image: mysql:5.5
   environment: 
    - MYSQL_ROOT_PASSWORD=root