version: '2'
services:
  web:
    image: vulhub/cmsms:2.2.9.1
    ports:
     - "80:80"
    depends_on:
     - db
  db:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cmsms
