version: '2'
services:
  web:
    image: vulhub/confluence:6.10.2
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    environment: 
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=confluence