version: '2'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - db
  db:
   image: postgres:9.6-alpine
   environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=cve