server.port=8080
spring.application.name=spring-boot-admin
spring.jmx.enabled=true
spring.cloud.compatibility-verifier.enabled=false

spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.username=vulhub
spring.mail.password=vulhub
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.boot.admin.notify.mail.enabled=false
spring.boot.admin.monitor.status-interval=2s
spring.boot.admin.monitor.status-lifetime=2s

management.server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.env.enabled=true
management.endpoint.env.show-values=always
management.endpoint.env.post.enabled=true
management.endpoint.health.show-details=always
management.endpoint.refresh.enabled=true
management.health.mail.enabled=false
