services:
 web:
   image: vulhub/craftcms:4.4.14
   depends_on:
    - db
   ports:
    - "8088:80"
 db:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=craftcms
