version: '2'
services:
  web:
    image: vulhub/v2board:1.6.1
    ports:
     - "8080:80"
    depends_on:
     - db
     - redis
    entrypoint:
     - bash
     - /entrypoint.sh
    volumes:
     - ./entrypoint.sh:/entrypoint.sh
    command: apache2-foreground
  db:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=v2board
  redis:
   image: redis:7-alpine
