version: '2'
services:
 web:
   image: vulhub/wordpress:4.6
   depends_on:
    - mysql
   environment: 
    - WORDPRESS_DB_HOST=mysql:3306
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=root
    - WORDPRESS_DB_NAME=wordpress
   ports:
    - "8080:80"
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
