services:
  discuz:
    image: vulhub/discuz:7.2
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: mysql:5.5
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discuz
