#!/bin/bash

export BIND_HOST=127.0.0.1
export BIND_PORT=9091
export WORK_DIR="/opt/jumpserver/chen"
export COMPONENT_NAME="chen"
export EXECUTE_PROGRAM="java -jar chen.jar"
export WISP_HOST=127.0.0.1
export WISP_PORT=9091

wait-for-it -t 0 127.0.0.1:8080 -- echo "core host is up"
/opt/jumpserver/wisp/wisp
