apiVersion: v1
kind: Secret
metadata:
  name: test-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: test-helm-repo
  url: https://charts.example.invalid
  type: helm
  project: myproject
  username: vulhub-bot
  password: s3cr3t-helm-pass-2025
