apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: ""
  policy.csv: |
    p, role:developer, projects, get, gitops-production, allow
    g, developer, role:developer
