version: '2'
services:
  couchdb:
    image: vulhub/couchdb:2.1.0
    ports:
      - "5984:5984"
    environment: 
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
  initd:
    image: buildpack-deps:focal-curl
    command: "bash /init.sh"
    environment: 
      COUCHDB_URL: couchdb:5984
      COUCHDB_AUTH: admin:password
    volumes:
      - ./init.sh:/init.sh
    depends_on:
      - couchdb
